- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: GitHub
  url: http://github.com/qveu
  class: icon-github
  title: Our code.

- name: Twitter
  url: http://twitter.com/drptdolan
  class: icon-twitter
  title: "QVEU on Twitter"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
